# Import Data and Look Around

- set up the dataframes
- take a look at their characteristics
- clean up as needed
- join as needed
- save cleaned and joined dataframes

# Import Libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Import and Setup Dataframes

In [7]:
outpatient_csv = '../data/tennessee_outpatient_clean.csv'
cbsa2name_csv = '../data/core-based-statistical-areas-cbsas-and-combined-statistical-areas-csas.csv'

cbsa_to_name = pd.read_csv(cbsa2name_csv, engine='python')
outpatient = pd.read_csv(outpatient_csv, 
                         dtype={"provider_name": object, "provider_street_address": object, "provider_city": object})

# NOTE: was getting an error so changed these dtypes on import. The ones that should be 'int' caused more errors
#       so they're commented out
#                          dtype={"provider_id": int, "provider_name": object, "provider_street_address": object, 
#                                 "provider_city": object, "provider_zip_code": int, "apc": int})

print(cbsa_to_name.info())
print(outpatient.info())
outpatient.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1918 entries, 0 to 1917
Data columns (total 15 columns):
CBSA Code                                     1918 non-null object
Metropolitan Division Code                    111 non-null object
CSA Code                                      1256 non-null object
CBSA Title                                    1916 non-null object
Metropolitan/Micropolitan Statistical Area    1915 non-null object
Metropolitan Division Title                   1915 non-null object
CSA Title                                     110 non-null object
County/County Equivalent                      1255 non-null object
State Name                                    1915 non-null object
FIPS State Code                               1915 non-null object
FIPS County Code                              1915 non-null object
Central/Outlying County                       1915 non-null object
columnm                                       1915 non-null object
columnn                                       1255 non-null object
columno                                       110 non-null object
dtypes: object(15)
memory usage: 224.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47417 entries, 0 to 47416
Data columns (total 23 columns):
Unnamed: 0                                   47417 non-null int64
provider_id                                  79 non-null float64
provider_name                                79 non-null object
provider_street_address                      79 non-null object
provider_city                                79 non-null object
provider_state                               79 non-null object
provider_zip_code                            79 non-null float64
provider_hospital_referral_region_(hrr)      79 non-null object
apc                                          79 non-null float64
apc_description                              79 non-null object
beneficiaries                                77 non-null float64
comprehensive_apc_services                   79 non-null float64
average_estimated_total_submitted_charges    79 non-null float64
average_medicare_allowed_amount              79 non-null float64
average_medicare_payment_amount              79 non-null float64
outlier_comprehensive_apc_services           73 non-null float64
average_medicare_outlier_amount              73 non-null float64
zip                                          47417 non-null int64
cbsa                                         47417 non-null int64
res_ratio                                    47417 non-null float64
bus_ratio                                    47417 non-null float64
oth_ratio                                    47417 non-null float64
tot_ratio                                    47417 non-null float64
dtypes: float64(14), int64(3), object(6)
memory usage: 8.3+ MB
None

,Unnamed: 0,provider_id,provider_name,provider_street_address,provider_city,provider_state,provider_zip_code,provider_hospital_referral_region_(hrr),apc,apc_description,...,average_medicare_allowed_amount,average_medicare_payment_amount,outlier_comprehensive_apc_services,average_medicare_outlier_amount,zip,cbsa,res_ratio,bus_ratio,oth_ratio,tot_ratio
0,0,440002.0,Jackson-Madison County General Hospital,620 Skyline Drive,Jackson,TN,38301.0,TN - Jackson,5302.0,Level 2 Upper GI Procedures,...,1141.086681,899.775086,0.0,0.0,38301,15140,0.000167,0.000428,0.0,0.000185
1,1,440002.0,Jackson-Madison County General Hospital,620 Skyline Drive,Jackson,TN,38301.0,TN - Jackson,5302.0,Level 2 Upper GI Procedures,...,1141.086681,899.775086,0.0,0.0,38301,27180,0.999833,0.999572,1.0,0.999815
2,2,440003.0,Sumner Regional Medical Center,555 Hartsville Pike,Gallatin,TN,37066.0,TN - Nashville,5302.0,Level 2 Upper GI Procedures,...,1223.454825,968.390614,0.0,0.0,37066,34980,1.000000,1.000000,1.0,1.000000
3,3,440006.0,Tristar Skyline Medical Center,3441 Dickerson Pike,Nashville,TN,37207.0,TN - Nashville,5302.0,Level 2 Upper GI Procedures,...,1248.620000,994.840000,0.0,0.0,37207,34980,1.000000,1.000000,1.0,1.000000
4,4,440009.0,Cumberland Medical Center,421 S Main St,Crossville,TN,38555.0,TN - Nashville,5302.0,Level 2 Upper GI Procedures,...,1152.663556,914.163556,0.0,0.0,38555,18900,1.000000,1.000000,1.0,1.000000

# Clean Up Column Names and Dtypes

In [9]:
# convert spaces to underscores and make lowercase
cbsa_to_name.columns = cbsa_to_name.columns.str.replace(' ', '_').str.lower()



# DEBUGDEBUG: This is not working cbsa_code is still an object, see below
# Cast CBSA code to numeric
cbsa_to_name['cbsa_code'] = pd.to_numeric(cbsa_to_name['cbsa_code'], errors='coerce')
print(cbsa_to_name.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1918 entries, 0 to 1917
Data columns (total 15 columns):
cbsa_code                                     1915 non-null float64
metropolitan_division_code                    111 non-null object
csa_code                                      1256 non-null object
cbsa_title                                    1916 non-null object
metropolitan/micropolitan_statistical_area    1915 non-null object
metropolitan_division_title                   1915 non-null object
csa_title                                     110 non-null object
county/county_equivalent                      1255 non-null object
state_name                                    1915 non-null object
fips_state_code                               1915 non-null object
fips_county_code                              1915 non-null object
central/outlying_county                       1915 non-null object
columnm                                       1915 non-null object
columnn                                       1255 non-null object
columno                                       110 non-null object
dtypes: float64(1), object(14)
memory usage: 224.9+ KB
None

# Join Files

In [4]:
outpatient = pd.merge(left=outpatient, right=cbsa_to_name, 
                                      left_on='cbsa', right_on='cbsa_code', how='inner')

print(outpatient.info())
outpatient.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 202424 entries, 0 to 202423
Data columns (total 38 columns):
Unnamed: 0                                    202421 non-null float64
provider_id                                   427 non-null float64
provider_name                                 427 non-null object
provider_street_address                       427 non-null object
provider_city                                 427 non-null object
provider_state                                427 non-null object
provider_zip_code                             427 non-null float64
provider_hospital_referral_region_(hrr)       427 non-null object
apc                                           427 non-null float64
apc_description                               427 non-null object
beneficiaries                                 425 non-null float64
comprehensive_apc_services                    427 non-null float64
average_estimated_total_submitted_charges     427 non-null float64
average_medicare_allowed_amount               427 non-null float64
average_medicare_payment_amount               427 non-null float64
outlier_comprehensive_apc_services            378 non-null float64
average_medicare_outlier_amount               378 non-null float64
zip                                           202421 non-null float64
cbsa                                          202421 non-null float64
res_ratio                                     202421 non-null float64
bus_ratio                                     202421 non-null float64
oth_ratio                                     202421 non-null float64
tot_ratio                                     202421 non-null float64
cbsa_code                                     191227 non-null float64
metropolitan_division_code                    68061 non-null object
csa_code                                      166471 non-null object
cbsa_title                                    191228 non-null object
metropolitan/micropolitan_statistical_area    191227 non-null object
metropolitan_division_title                   191227 non-null object
csa_title                                     68060 non-null object
county/county_equivalent                      166470 non-null object
state_name                                    191227 non-null object
fips_state_code                               191227 non-null object
fips_county_code                              191227 non-null object
central/outlying_county                       191227 non-null object
columnm                                       191227 non-null object
columnn                                       166470 non-null object
columno                                       68060 non-null object
dtypes: float64(18), object(20)
memory usage: 60.2+ MB
None

,Unnamed: 0,provider_id,provider_name,provider_street_address,provider_city,provider_state,provider_zip_code,provider_hospital_referral_region_(hrr),apc,apc_description,...,metropolitan_division_title,csa_title,county/county_equivalent,state_name,fips_state_code,fips_county_code,central/outlying_county,columnm,columnn,columno
0,0.0,440002.0,Jackson-Madison County General Hospital,620 Skyline Drive,Jackson,TN,38301.0,TN - Jackson,5302.0,Level 2 Upper GI Procedures,...,Micropolitan Statistical Area,NaN,Jackson-Brownsville,TN,Haywood County,Tennessee,47,75,Central,NaN
1,17633.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Micropolitan Statistical Area,NaN,Jackson-Brownsville,TN,Haywood County,Tennessee,47,75,Central,NaN
2,17637.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Micropolitan Statistical Area,NaN,Jackson-Brownsville,TN,Haywood County,Tennessee,47,75,Central,NaN
3,17655.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Micropolitan Statistical Area,NaN,Jackson-Brownsville,TN,Haywood County,Tennessee,47,75,Central,NaN
4,17670.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Micropolitan Statistical Area,NaN,Jackson-Brownsville,TN,Haywood County,Tennessee,47,75,Central,NaN

# Look at data
- .info()
- .head()
- .tail()
- .shape

# Drop Extra Columns

In [5]:
# Drop all but listed tables for outpatient
outpatient_clean = outpatient[[
    'provider_name',
    'apc',
    'apc_description',
    'beneficiaries',
    'comprehensive_apc_services',
    'average_estimated_total_submitted_charges',
    'average_medicare_allowed_amount',
    'average_medicare_payment_amount',
    'average_medicare_outlier_amount',
    'zip',
    'cbsa',
    'cbsa_title']]
# outpatient = outpatient.dropna()
outpatient

,Unnamed: 0,provider_id,provider_name,provider_street_address,provider_city,provider_state,provider_zip_code,provider_hospital_referral_region_(hrr),apc,apc_description,...,metropolitan_division_title,csa_title,county/county_equivalent,state_name,fips_state_code,fips_county_code,central/outlying_county,columnm,columnn,columno
0,0.0,440002.0,Jackson-Madison County General Hospital,620 Skyline Drive,Jackson,TN,38301.0,TN - Jackson,5302.0,Level 2 Upper GI Procedures,...,Micropolitan Statistical Area,NaN,Jackson-Brownsville,TN,Haywood County,Tennessee,47,75,Central,NaN
1,17633.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Micropolitan Statistical Area,NaN,Jackson-Brownsville,TN,Haywood County,Tennessee,47,75,Central,NaN
2,17637.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Micropolitan Statistical Area,NaN,Jackson-Brownsville,TN,Haywood County,Tennessee,47,75,Central,NaN
3,17655.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Micropolitan Statistical Area,NaN,Jackson-Brownsville,TN,Haywood County,Tennessee,47,75,Central,NaN
4,17670.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Micropolitan Statistical Area,NaN,Jackson-Brownsville,TN,Haywood County,Tennessee,47,75,Central,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202419,47405.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Micropolitan Statistical Area,NaN,NaN,Ketchikan Gateway Borough,Alaska,2,130,Central,NaN,NaN
202420,47415.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Micropolitan Statistical Area,NaN,NaN,Ketchikan Gateway Borough,Alaska,2,130,Central,NaN,NaN
202421,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202422,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202423,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN